// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnnznssNSiQGBpiGoV_AdXsx-kE8-o_xg',
    appId: '1:797109856548:web:7f228193c1193f028f2bb1',
    messagingSenderId: '797109856548',
    projectId: 'privichat-71c1f',
    authDomain: 'privichat-71c1f.firebaseapp.com',
    databaseURL: 'https://privichat-71c1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'privichat-71c1f.appspot.com',
    measurementId: 'G-H5LBH1DVQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt0y6JgBZj4_imylD_qseQHhNUZ1FXVY0',
    appId: '1:797109856548:android:fc7e1e7a71b80e288f2bb1',
    messagingSenderId: '797109856548',
    projectId: 'privichat-71c1f',
    databaseURL: 'https://privichat-71c1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'privichat-71c1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCMyt8PqUfJrydkXWhiMbRz9w_asqlH3E',
    appId: '1:797109856548:ios:df698fc5986294978f2bb1',
    messagingSenderId: '797109856548',
    projectId: 'privichat-71c1f',
    databaseURL: 'https://privichat-71c1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'privichat-71c1f.appspot.com',
    iosBundleId: 'com.example.privichatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCMyt8PqUfJrydkXWhiMbRz9w_asqlH3E',
    appId: '1:797109856548:ios:49f904ea5b579d798f2bb1',
    messagingSenderId: '797109856548',
    projectId: 'privichat-71c1f',
    databaseURL: 'https://privichat-71c1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'privichat-71c1f.appspot.com',
    iosBundleId: 'com.example.privichatFlutter.RunnerTests',
  );
}
